package:
   name: numba-scipy
   version: {{ GIT_DESCRIBE_TAG }}

source:
   path: ../../..

build:
  number: {{ GIT_DESCRIBE_NUMBER|int }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  # build and run dependencies are duplicated to avoid setuptools issues
  # when we also set install_requires in setup.py
  build:
    - git
  host:
    - python
    - numba
    - scipy==1.4.*
    - setuptools
  run:
    - python
    - numba
    - scipy==1.4.*

test:
  requires:
    - scipy==1.4.*
    - pytest
    - setuptools
    - faulthandler             # [py27 and (not (armv6l or armv7l))]

about:
  home: https://github.com/numba/numba-scipy
  license: BSD
  license_file: LICENSE
  summary: numba-scipy extends Numba to make it aware of SciPy
